# Generated by Django 6.0.7 on 2026-07-20 17:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('PROGRAMMING', 'Programming')], default='MCQ', max_length=20)),
                ('question', models.TextField()),
                ('option_a', models.CharField(blank=True, max_length=500, null=True)),
                ('option_b', models.CharField(blank=True, max_length=500, null=True)),
                ('option_c', models.CharField(blank=True, max_length=500, null=True)),
                ('option_d', models.CharField(blank=True, max_length=500, null=True)),
                ('correct_answer', models.CharField(blank=True, help_text="'A', 'B', 'C', or 'D' for MCQ. Null for PROGRAMMING.", max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
    ]
