# Generated by Django 6.0.7 on 2026-07-20 17:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.CharField(help_text='Backblaze B2 key for the resume file', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'resumes',
            },
        ),
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extracted_name', models.CharField(blank=True, max_length=255, null=True)),
                ('extracted_email', models.CharField(blank=True, max_length=255, null=True)),
                ('extracted_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('extracted_website', models.CharField(blank=True, max_length=255, null=True)),
                ('extracted_linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('extracted_github', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.JSONField(blank=True, null=True)),
                ('experience', models.JSONField(blank=True, null=True)),
                ('projects', models.JSONField(blank=True, null=True)),
                ('certifications', models.JSONField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('extracted_skills', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'resume_analyses',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.FloatField(blank=True, help_text='AI computed match score percentage', null=True)),
                ('matched_skills', models.JSONField(blank=True, null=True)),
                ('missing_skills', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('aptitude_round', 'Aptitude Round'), ('technical_round', 'Technical Round'), ('face_to_face_interview', 'Face to Face Interview'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_role', models.ForeignKey(db_column='job_role_id', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobrole')),
            ],
            options={
                'db_table': 'applications',
            },
        ),
    ]
