# Generated by Django 6.0.7 on 2026-07-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_location',
            field=models.CharField(blank=True, default='Abc company chennai', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
