# Generated by Django 6.0.7 on 2026-07-20 17:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequiredSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.CASCADE, to='skills.skill')),
            ],
            options={
                'db_table': 'job_required_skills',
            },
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_education', models.CharField(blank=True, max_length=100, null=True)),
                ('min_experience', models.IntegerField(blank=True, help_text='Minimum experience required in years', null=True)),
                ('last_application_date', models.DateField(blank=True, help_text='Last date to submit an application', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_skills', models.ManyToManyField(blank=True, related_name='job_roles', through='jobs.JobRequiredSkill', to='skills.skill')),
            ],
            options={
                'db_table': 'job_roles',
            },
        ),
        migrations.AddField(
            model_name='jobrequiredskill',
            name='job',
            field=models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='jobs.jobrole'),
        ),
        migrations.AlterUniqueTogether(
            name='jobrequiredskill',
            unique_together={('job', 'skill')},
        ),
    ]
